server:
  port: 9400

logging:
  level:
    com:
      infp:
        ciat: debug

fileserver:
  token: ENC(lpQnVzxYt5RYQfHU2aB50g9XHMsyFyZKF1PbTzkiyTyxLNioX44bkNo2VgaH4F1CK2yK14wT3PKZa0NMthM/6Q==)
  host: ENC(k3tmhbeB0P8X1diQm8rOaos8WDukKF0Y2do8eeBTniRop33Smr5TzedPQPjL6cFuEOED6QPQSexYrO5198uJ+w==)

jwt:
  secret: ENC(Cl3BCNpeRSj6N+1+TG34TJhNHLjnsRVXzm+cRmItlJWh4HEzErp2SX+05e9F5wys1OewnGWMWb3eJ06jUbcnOw==)
  # hour
  lifetime: 12

spring:
  datasource:
    url: ENC(k0LDmCtzrFfqWHag/q4FDHr1sAsTipWHEML6wH6hgG43fDmoTJGlCKmk4iOCw/lpZuI3PCeGO4yMNgtmOf0CEH6RCQyyOldEvsaMg/XsCbpih7yOrM78pl0SZqZe9WxMA2dFzYtnuOrMZmeaQ9l2dA==)
    driver-class-name: ENC(oxBFRuSb4koRfQC9Gf0sxTwdrHOYkUj4WEin05x4Shye5KO3Z4GDhj8Og40V7uhUEbKg+nLdIKcZ9Nvys9Z3jA==)
    username: ENC(ZkOJwQDP0e0TmKw1nGbX7Ba1o6KYQW3wBLovkvlRV9jM2+XUYA8JP8sgv5k5ND2c)
    password: ENC(pTR+Lp1bqtulUeZR8siprgfFg7Sjsz4nl1aOd4HqEG4lrUB3OUacN9ZwtvfVuPlNFv58HeodTi2mh2kB73K/Ww==)
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      database-platform: ENC(Aig0iPZvJyD6FXVBfrCD6FgvfUkiHKqlF9bshJ6LQGuD4MnBsryj71pstaL9rFtoY/YBvgFMtg9KafpZON4KYztVqW0mYG7ZdHo1PpxCLXs=)

#공공포탈 api service key, public url
forest:
  public: ENC(S9uh+jA+zZaejBjNJaIT4B7HQpv6QYqSVp//6MHWyM5MA9hOEd1LZWaRtvaMqd5jIatENDOp00cu/YhT8lrf9KlCmVQ5h20JT4CWHNUiz3Lxnr3OXUuU80UPdGhXgYiM)
  serviceKey: ENC(aFEsybz29ctGAqxPNnPdFTixfvFe3EenJFOyBWsHtDB6AtqZ0TOgqoOPSokjSo9syTREbCaN6/NXsLSnv4ml+UQsusSxaaACfM9JE5dDigAQLHNALMlr4K4GqageYzcRjcZF6PGDGpQkAqYOMsJLoc6ra8dURKlyIVQpGpgbAHNCKORnDir/6mlkZdRxqR1q)